<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="Package">
		<Title>NET Project Package Extractor</Title>
		<Description>A command line application that extracts all nuget information from csproj files in a nested directory structure and saves the result to a spreadsheet.</Description>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<PackAsTool>true</PackAsTool>
		<PackageId>nppe</PackageId>
		<ToolCommandName>nppe</ToolCommandName>
		<PackageOutputPath>./nupkg</PackageOutputPath>
		<Version>4.0.0</Version>
		<ImplicitUsings>disable</ImplicitUsings>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>starion-s-symbol-main1-rgb.png</PackageIcon>
        <PackageReleaseNotes>
            [Update] Dependencies
        </PackageReleaseNotes>
	</PropertyGroup>

	<PropertyGroup Label="Copyright">
		<Company>Starion Group S.A.</Company>
		<Copyright>Copyright 2022-2024 Starion Group S.A.</Copyright>
		<Authors>Sam Gerené, Alexander van Delft</Authors>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<RequireLicenseAcceptance>true</RequireLicenseAcceptance>
	</PropertyGroup>

	<PropertyGroup Label="Repository">
		<RepositoryUrl>https://github.com/STARIONGROUP/Net-Project-Package-Extractor.git</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
	</PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\ascii-art.txt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\ascii-art.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

	<ItemGroup>		
		<PackageReference Include="ClosedXML" Version="0.105.0" />		
		<PackageReference Include="NuGet.Packaging" Version="6.14.0" />
		<PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
		<PackageReference Include="System.CommandLine.Hosting" Version="0.4.0-alpha.22272.1" />
		<PackageReference Include="Spectre.Console" Version="0.51.1" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Commands\" />
	</ItemGroup>

    <ItemGroup>
        <None Include="..\starion-s-symbol-main1-rgb.png" Pack="true" PackagePath="" />
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
