<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
	<Company>Starion Group S.A.</Company>
	<Authors>Sam Gerené, Alexander van Delft</Authors>
	<Copyright>Copyright 2022-2024 Starion Group S.A.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="NUnit" Version="4.4.0" />
	<PackageReference Include="NUnit.Console" Version="3.20.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.2.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	<PackageReference Include="coverlet.msbuild" Version="6.0.4">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="Root\SubFolder1\Subfolder1.1\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Root\root.csproj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
	<None Include="Root\SubFolder1\SubFolder1.csproj">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Include="Root\SubFolder1\Subfolder1.1\SubFolder1.1.csproj">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetProjectPackageExtractor\NetProjectPackageExtractor.csproj" />
  </ItemGroup>
</Project>
